### ISSUE TITLE
Kahoot reject authentication request: Unknown Client

### ISSUE THREAD

**Issue by adamsong** [Arccotangent/kahoot-hack#1]
When connecting to a kahoot game I get the error: 
    `[{"error":"402::Unknown client","successful":false,"advice":{"interval":0,"reconnect":"handshake"},"channel":"/meta/connect"}]`

**Comment by Arccotangent** [comment]
Looking into this, Kahoot has had some changes since this tool was updated.
I should have the tool fixed very soon.

**Comment by Arccotangent** [comment]
I've just confirmed that the tool is working again, closing this issue.
