### ISSUE TITLE
Handshake URL: Illegal Character

### ISSUE THREAD

**Issue by IncognitoJam** [Arccotangent/kahoot-hack#2]
When running the "App" program, choosing either [1] Play Normally or [2] Flood, this error occurs:

> Exception in thread "main" java.lang.IllegalArgumentException: Illegal character in path at index 36: https://kahoot.it/cometd/869157/:cc4<e5?e6l54403;f:fe88=;a9ake564aja2e4a:abe6591ef92hf0726?06023=e:4ea
> m<g>e6866?gehgb396hfe1`7<3/handshake
>         at java.net.URI.create(URI.java:852)
>         at org.apache.http.client.methods.HttpPost.<init>(HttpPost.java:76)
>         at net.arccotangent.kahoothack.HTTP.POST(HTTP.java:26)
>         at net.arccotangent.kahoothack.Kahoot.initialize(Kahoot.java:210)
>         at net.arccotangent.kahoothack.App.main(App.java:32)
> Caused by: java.net.URISyntaxException: Illegal character in path at index 36: https://kahoot.it/cometd/869157/:cc4<e5?e6l54403;f:fe88=;a9ake564aja2e4a:abe6591ef92hf0726?06023=e:4eam<g>e6866?gehgb396hfe1`
> 7<3/handshake
>         at java.net.URI$Parser.fail(URI.java:2848)
>         at java.net.URI$Parser.checkChars(URI.java:3021)
>         at java.net.URI$Parser.parseHierarchical(URI.java:3105)
>         at java.net.URI$Parser.parse(URI.java:3053)
>         at java.net.URI.<init>(URI.java:588)
>         at java.net.URI.create(URI.java:850)
>         ... 4 more

Full stacktrace: http://pastebin.com/y0Du0cpe

I have tried this multiple times with different games and usernames, and the same error occurs.

Great work on this, and I hope to see it fully functioning soon!

**Comment by IncognitoJam** [comment]
I noticed an error in the challenge calculation, please see #3

**Comment by Arccotangent** [comment]
Pull request #3 merged, closing this issue.
